# Database
server.port=8081
spring.profiles.default=local
spring.datasource.url=jdbc:postgresql://localhost:5432/sweProjectDB
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.sql.init.mode=always

# JWT

jwt.secret=${JWT_SECRET:v8y/B?E(H+MbQeThWmZq4t7w!z%C&F)J}
jwt.expiration=86400000

# Stripe
stripe.secret.key=${STRIPE_SECRET_KEY:sk_test_ReplaceMeWithYourStripeSecretKey}
stripe.publishable.key=${STRIPE_PUBLISHABLE_KEY:pk_test_ReplaceMeWithYourStripePublishableKey}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:whsec_ReplaceMeWithYourWebhookSecret}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.root=warn
logging.level.com.crms=DEBUG
spring.main.banner-mode=off
